branch-defaults:
  aws:
    environment: simpleserver
    group_suffix: null
environment-defaults:
  simpleserver:
    branch: null
    repository: null
global:
  application_name: simpleserver
  branch: null
  default_ec2_keyname: vito
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  repository: null
  sc: git
